# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip
require 'fileutils'
require 'pathname'
require 'tmpdir'

platform :ios, '17.5'
prepare_react_native_project!

pre_install do |_installer|
  local_xcframework = File.expand_path('../../ios/Frameworks/HawcxFramework.xcframework', __dir__)
  pod_xcframework   = File.expand_path('../node_modules/@hawcx/react-native-sdk/ios/Frameworks/HawcxFramework.xcframework', __dir__)

  unless File.exist?(local_xcframework)
    Pod::UI.warn "Local HawcxFramework not found at #{local_xcframework}; using packaged release."
    next
  end

  Pod::UI.puts "🔄 Syncing local HawcxFramework.xcframework into node_modules copy"
  temp_dir = Dir.mktmpdir('hawcx-framework-copy')
  temp_framework = File.join(temp_dir, 'HawcxFramework.xcframework')

  FileUtils.cp_r(Pathname.new(local_xcframework).realpath.to_s, temp_framework)
  FileUtils.rm_rf(pod_xcframework)
  FileUtils.mkdir_p(File.dirname(pod_xcframework))
  FileUtils.cp_r(temp_framework, pod_xcframework)
ensure
  FileUtils.rm_rf(temp_dir) if defined?(temp_dir) && temp_dir && Dir.exist?(temp_dir)
end

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = FlipperConfiguration.disabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'HawcxExampleApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'HawcxExampleAppTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
